# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aeae05fe2f8d9736043cf86b6ab076824a67bcb57d8dd21f4bbf86bbfbea89fb11b9bc685714136fe9657f22bb71769c3717ce119cfb56f855179643f04236b

test:
  secret_key_base: 4928c4603c08fbb2941fa7a4f2c6f8cb3b41a05aea15af0159e1879f39ba8f9313af3819276d44a41ca5bd334374f2eac148671126d619aa5f3d38216432e182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
